[project]
name = "bothackathon"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
    "google-genai>=1.3.0",
    "pytelegrambotapi>=4.26.0",
]

[dependency-groups]
dev = [
    "ipython>=9.0.0",
]
